const dummyAdData = [
    // Shoes
    {
      company_name: "flipkart",
      profile_pic: "https://i.pinimg.com/originals/aa/70/8d/aa708d1f97a04f6f5a208213f89e1e67.png",
      product_description: "High-quality leather shoes for formal events.",
      website_url: "https://www.flipkart.com/search?q=shoes&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off",
      product_img: "https://i.pinimg.com/564x/da/e1/43/dae14306dad1e66614186388f4900463.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Trendy sneakers for casual wear.",
      website_url: "https://www.amazon.in/s?k=shoes&crid=31VK2IJQHWRDL&sprefix=shoes%2Caps%2C483&ref=nb_sb_noss_1",
      product_img: "https://i.pinimg.com/564x/88/f1/10/88f1109c90e5a75809005301e95e7d39.jpg",
    },
    {
      company_name: "Nike",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV83ewYe_Far2cqyU5t-UugdM7zO4BLlscDw&s",
      product_description: "Nike-300-fit-man ,Lightweight running shoes for fitness enthusiasts.",
      website_url: "https://www.nike.com/in/",
      product_img: "https://i.pinimg.com/236x/81/30/9d/81309db5b059db083c09d611de8b89cb.jpg",
    },
    {
      company_name: "Meesho",
      profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
      product_description: "Elegant dress shoes.",
      website_url: "https://www.meesho.com/search?q=shoes&searchType=manual&searchIdentifier=text_search",
      product_img: "https://i.pinimg.com/236x/77/9a/a8/779aa8b699bdf10ce3f9d4c7e8aca4df.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Comfortable everyday shoes for long hours.",
      website_url: "https://www.amazon.in/s?k=shoes&crid=31VK2IJQHWRDL&sprefix=shoes%2Caps%2C483&ref=nb_sb_noss_1",
      product_img: "https://i.pinimg.com/564x/42/b4/08/42b40824441ea9f71019516353dd490a.jpg",
    },
  
    // Clothes
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Chic summer dresses for casual outings. Buy Angashion Women's Dresses-Summer Floral Bohemian Spaghetti Strap Button Down Swing Midi Dress and other Casual at Amazon.com.",
      website_urcoml: "https://www.amazon.com/Angashion-Dresses-Summer-Bohemian-Spaghetti-Pockets/dp/B07BTKX7DT/ref=sr_1_11?s=apparel&sr=1-11",
      product_img: "https://i.pinimg.com/236x/3a/27/6f/3a276fb307fbb45337ca6a5b3c081e26.jpg",
    },
    {
      company_name: "Urban Wear",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9kltoOjMq8OSmhzjpruBQKZ4OuA7-W9LTBw&s",
      product_description: "Trendy t-shirts and jeans for urban lifestyle.Try our Dark Wash Casual Collar Long Sleeve Denim Plain Shirt Embellished Non-Stretch Men Denim",
      website_url: "https://urbanwear.com",
      product_img: "https://i.pinimg.com/564x/da/8b/c2/da8bc2ff56f3baa19a58d9ef7f247e2d.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Luxury clothing for special occasions. Try our V Neck Bridesmaid Dresses Long Chiffon Ruffle Sleeves Formal Evening Wedding Party Dress for Women with Slit",
      website_url: "https://www.amazon.com/kidadndy-Bridesmaid-Dresses-Chiffon-Pleated/dp/B0BLBDC2L2/ref=asc_df_B0BLBDC2L2?hvdev=m&hvpone=626746607077&hvptwo=2680072505217&hvqmt=4260607978637&hvadid=4672928963646&psc=1&pp=1",
      product_img: "https://i.pinimg.com/564x/25/1a/ae/251aae7a993bb256f704b3fbbded4683.jpg",
    },
    {
      company_name: "Next",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStlnHLAgxXcNAiYECKHk5nQXe9oXudQTO-1Q&s",
      product_description: "Relaxed and comfortable clothing for night wear.",
      website_url: "https://www.next.co.uk/shop/gender-men-productaffiliation-nightwear-0?p=2#438.03125",
      product_img: "https://i.pinimg.com/236x/68/38/83/683883e23f23b09ea888ea2defea96af.jpg",
    },
    {
      company_name: "Outdoor Gear",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoBPB0nk7RfQqcdaLslrFc3bDxjjZKeLk8GQ&s",
      product_description: "Durable and rugged Bag for outdoor activities. To make your Tracking smoother than the butter",
      website_url: "https://outdoorgear.com",
      product_img: "https://i.pinimg.com/236x/b1/2f/73/b12f733ce63d9c837a338ad687e6c2f4.jpg",
    },
    {
      company_name: "Get Trend ",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Xn3ZeAKy9pqwOzbkJ-6rmcni5csUNdhPdg&s",
      product_description: "CityComfort Mens Pyjamas Set - Mens Nightwear, Relaxed and comfortable clothing for night wear",
      website_url: "https://gettrend.com/products/citycomfort-mens-pyjamas-set-cotton-mens-nightwear?variant=43320267407617",
      product_img: "https://i.pinimg.com/236x/f1/f9/c0/f1f9c0627b05fee345938ec6d4785b66.jpg",
    },
    // Electric Appliances
    {
      company_name: "Samsung",
      profile_pic: "https://w7.pngwing.com/pngs/176/171/png-transparent-samsung-galaxy-gurugram-faridabad-logo-samsung-blue-text-logo.png",
      product_description: "11 LBS Portable Full-Automatic Washing Machine Compact 1.5 Cubic Feet Laundry Washer Spin with LED Display. White High-performance washing machines and dryers.",
      website_url: "https://www.samsung.com/in/aisearch/?searchvalue=Washing%20Machines",
      product_img: "https://i.pinimg.com/236x/49/6c/ef/496cef2f307385a0580ef2d4ab3fffc0.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "APPLE IPHONE 15 PRO 128GB NATURAL TITANIUM: the latest iteration of Apple's flagship smartphone, the iPhone 15 represents a significant investment for many consumers. With its cutting-edge features, impressive performance, and sleek design",
      website_url: "https://www.amazon.in/Apple-iPhone-15-128-GB/dp/B0CHX1W1XY/ref=sr_1_1_sspa?nsdOptOutParam=true&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
      product_img: "https://i.pinimg.com/564x/19/db/99/19db996e9bc7a474cadbd74eed747443.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "MrCool Easy Pro 12k BTU 18 SEER Ductless Heat Pump Split System - DIY Mini Split w/ 16ft Lineset #heatpump #airconditioning #airconditioner. Energy-efficient air conditioners for all seasons.",
      website_url: "https://www.amazon.com/dp/B0B1F74DHF/ref=cm_sw_r_as_gl_api_gl_i_4HK9R1G7P9XSYGREPKPQ",
      product_img: "https://i.pinimg.com/736x/65/0b/25/650b253452208f947c29e56850e6e0ed.jpg",
    },
    {
      company_name: "Samsung",
      profile_pic: "https://w7.pngwing.com/pngs/176/171/png-transparent-samsung-galaxy-gurugram-faridabad-logo-samsung-blue-text-logo.png",
      product_description: "explore over-the-range, countertop, built-in microwaves & microwave ovens. Samsung microwaves have smart features like touch screen, vent, wifi & more..",
      website_url: "https://www.samsung.com/in/microwave-ovens/all-microwave-ovens/",
      product_img: "https://i.pinimg.com/564x/cb/99/02/cb9902b6db36776fc8b9a8b2775a486c.jpg",
    },
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Blink Video Doorbell | Two-way audio, HD video, motion and chime app alerts and Alexa enabled — wired or wire-free (Black)",
      website_url: "https://www.amazon.com/Blink-Video-Doorbell/dp/B08SG2MS3V?psc=1&linkId=5b18f1c510a3188132556024f2c720e4&language=en_US&ref_=as_li_ss_tl",
      product_img: "https://i.pinimg.com/564x/f8/47/fe/f847fedc37de586e5e4f99aadadc46b3.jpg",
    },
  
    // Women Accessories
    {
      company_name: "Amazon",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
      product_description: "Cubic Zirconia Flower Charm Necklace Free Returns ✓ Free Shipping✓. Cubic Zirconia Flower Charm Necklace- Women Pendant Necklaces at SHEIN.Elegant jewelry pieces for all occasions.",
      website_url: "https://www.amazon.com/s?k=necklaces+for+women",
      product_img: "https://i.pinimg.com/564x/cb/ba/d3/cbbad3886d9cab5260806b3163636650.jpg",
    },
    {
      company_name: "Meesho",
      profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
      product_description: "CN - 2021 SHOULDER BAG FOR WOMEN SB017 - Khaki / 29 X 11 X 21 CM PRODUCT DETAILS Shape: SatchelsHandbags Type: Shoulder BagsTypes of bags: Shoulder & HandbagsMain Material:",
      website_url: "https://www.meesho.com/search?q=handbags&searchType=manual&searchIdentifier=text_search",
      product_img: "https://i.pinimg.com/564x/73/37/54/7337545948f848959d2b3b778bcad23f.jpg",
    },
    {
      company_name: "Meesho",
      profile_pic: "https://picsum.photos/640/480?random=18",
      product_description: "Trendy sunglasses for fashion-conscious individuals.",
      website_url: "https://www.meesho.com/search?q=sunglasses&searchType=autosuggest&searchIdentifier=text_search",
      product_img: "https://i.pinimg.com/564x/84/88/69/848869a89e7a2fb199510191799f3251.jpg",
    },
    {
      company_name: "Breda",
      profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7izts8SXc_V6ZeAIeM7VZbYbj_ooHJCsSZA&s",
      product_description: "Jane (Taylor LaShae Exclusive), Stylish watches to match any outfit.",
      website_url: "https://www.breda.com/products/breda-jane-exclusive-1741f-tl-taylor-lashae-gold-watch?epik=dj0yJnU9cWgwdjhWQk1hbHlhMXpLS2g3UUNISzNBZ3RQLVoyRXAmcD0wJm49cW9LZElJWWRnTm43NkM3bW1nMTByUSZ0PUFBQUFBR2Jlc3FZ",
      product_img: "https://i.pinimg.com/564x/75/59/e6/7559e6477157217044bfb4a22501ba6b.jpg",
    },
    {
      company_name: "Meesho",
      profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
      product_description: "Infinity crystal rhinestone bracelet sliver and Wide variety of fashion accessories for women.",
      website_url: "https://www.meesho.com/search?q=bracelate&searchType=autosuggest&searchIdentifier=text_search",
      product_img: "https://i.pinimg.com/736x/ea/26/37/ea2637525224a9543bb49bdeafb90b36.jpg",
    },
    {
          company_name: "Flipkart",
          profile_pic: "https://i.pinimg.com/originals/aa/70/8d/aa708d1f97a04f6f5a208213f89e1e67.png",
          product_description: "Luxury wristwatches for men and women.",
          website_url: "https://www.flipkart.com/search?q=watches&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off",
          product_img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/i/r/w/1-ld-bk0054-black-silicone-strap-black-rustet-men-original-imahfs3kjxjsfa8m.jpeg?q=70",
        },
        {
          company_name: "Amazon",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
          product_description: "TIMEWEAR Analog Slim Two Hands Leather Strap Watches for Men. Vintage watches with timeless elegance.",
          website_url: "https://www.amazon.in/TIMEWEAR-Analog-Hands-Brown-Leather/dp/B07DN93B9R/ref=sr_1_20?crid=MWE3RE1WMF36&dib=eyJ2IjoiMSJ9.bGuCVUkFof_56VO5Q_7omRC8bbKdSR2cl1TZpePl1guozRq20TWEoMQfO7Yl8W9BSwIuWrQkT1r-WqzyrzsJNx3YuSgxbZwS0SrbmV3dD9Ng7vgAXiQRMvWf5TIrSoAg_dczabVBqXurvz85n74TqNF_ZOY5NZnt5pTjaoVJdaXPEcFIaZIcArIGQ4FUNyq4pDwiNz7c8YT4APD6o43FvfGBc8PzymNneTofJZWkvuMCGdJ-wlQLb9z6vrW7KIVlThHUc5_hjg2pMjRhXXjtqSv0QoDvfmrb5RsZrk340cQ.DQ7N4gJRZ9jbGqCpJ_g91BDT3xrRZH-KbnFsIrVvP_0&dib_tag=se&keywords=watches+for+men&qid=1725872082&sprefix=watch%2Caps%2C613&sr=8-20",
          product_img: "https://m.media-amazon.com/images/I/81CwsCvUWqL._SY679_.jpg",
        },
        {
          company_name: "Flipkart",
          profile_pic: "https://i.pinimg.com/originals/aa/70/8d/aa708d1f97a04f6f5a208213f89e1e67.png",
          product_description: "Motugaju Digital Sports 50m Waterproof LED Military Smart Stopwatch Countdown Digital Watch - For Men Date Alarm Shockproof Watches for Men's Kids Watch for Boys ",
          website_url: "https://www.flipkart.com/motugaju-digital-sports-50m-waterproof-led-military-smart-stopwatch-countdown-watch-men/p/itm5a1f3224504a3?pid=WATGXN72PXHYV3HZ&lid=LSTWATGXN72PXHYV3HZQHMUYJ&marketplace=FLIPKART&q=sports+watches+for+men&store=r18%2Ff13&srno=s_1_8&otracker=AS_QueryStore_OrganicAutoSuggest_1_13_sc_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_13_sc_na_ps&fm=search-autosuggest&iid=7dee5057-e8ab-497e-a8c5-5ff3e8d574ff.WATGXN72PXHYV3HZ.SEARCH&ppt=sp&ppn=sp&ssid=94mqc76jgg0000001725871864630&qH=f34dc49263e77250",
          product_img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/p/e/k/1-date-alarm-shockproof-watches-for-men-s-kids-watch-for-boys-original-imagqg4gayasnupy.jpeg?q=70",
        },
        {
          company_name: "Meesho",
          profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
          product_description: " New Fancy Solid Dial Attractive Metal Chain Attractive Bracelet Analog Watch for Women",
          website_url: "https://www.meesho.com/new-fancy-solid-dial-attractive-metal-chain-attractive-bracelet-analog-watch-for-women/p/66qy07",
          product_img: "https://images.meesho.com/images/products/374131879/yvvan_512.webp",
        },
        {
          company_name: "Amazon",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
          product_description: "LOUIS DEVIN Silicone Strap Analog Wrist Watch for Men (Black/Blue/Red) | LD-BK054.",
          website_url: "https://www.amazon.in/s?k=watches+for+men",
          product_img: "https://m.media-amazon.com/images/I/61LO6l4zB4L._SX679_.jpg",
        },
      
        // Men Ethnic Wear
        {
          company_name: "Amazon",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
          product_description: "N.B.F Fashion Mens Ethnic Wear Indo Western Set",
          website_url: "https://www.amazon.in/N-B-F-Fashion-Ethnic-Western-X-Large/dp/B09872TPTS/ref=sr_1_2_sspa?crid=3GR7BS9A6ZAGW&dib=eyJ2IjoiMSJ9.PDBoiTn4pQDG7sBmZYIEVZmorcAeojyX1P6sAa-kcqsEehCu4OXw6lY-7pLtFyGZI3yZUtfGI9DCUB-dzTy8Tu7ltm3OFhDJn__4n7ZGzpJQSR1b8c3I9WvuJhYs7wpMNcovcRO9uU3o_QIxzafqzWC6YRTTgGN_h3evOt1uoMNOkrtW4xnKH5oAcP2FFjc7ev7ACH7yPSf5mTrLsknawCQy45esIArx0DHXixV6MBiIGnxJkXSy6x-YAaFuTdj1sPo1XZeDtlTQVR9jdr2TS9yf-5jek6j50SGWJtppHBg.YplSqj75PoHAmn7QMKqMx8S6XjvRnHUWj4pQovbtNlw&dib_tag=se&keywords=men+ethnic+wear&qid=1725872387&sprefix=men+ethni%2Caps%2C297&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
          product_img: "https://m.media-amazon.com/images/I/81qjm0OlzmS._SY741_.jpg",
        },
        {
          company_name: "Manyavar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description:"Jamun Purple Sequin Embellished Chikankari Kurta Set",
          website_url: "https://www.manyavar.com/en-in/kurta-pajama/jamun-purple-sequin-embellished-chikankari-kurta-set/UC117602.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/CPOSK612_313-PURPLE.11517_26-08-2023-22-05:650x900",
        },
        {
          company_name: "Manyavar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description:"Mustard Yellow Embroidered Neckline Short Kurta",
          website_url: "https://www.manyavar.com/en-in/kurta/mustard-yellow-embroidered-neckline-short-kurta/UC109183.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/MLS101-328_03-05-2024-16-00:283x395",
        },{
          company_name: "Manyavar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description:"Rust Embroidery Blended Viscose Kurta Pajama",
          website_url: "https://www.manyavar.com/en-in/kurta-pajama/rust-embroidery-blended-viscose-kurta-pajama/UC131557.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/SOSK750_332-Rust.0588_22-04-2024-16-30:650x900",
        },{
          company_name: "Manyavar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description:"Maroon Harlequin Printed Short Kurta",
          website_url: "https://www.manyavar.com/en-in/kurta/maroon-harlequin-printed-short-kurta/UC117435.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/MLS067-307-Maroon.12472_20-03-2024-16-27:650x900",
        },
      
        // Women Ethnic Wear
        {
          company_name: "Meesho",
          profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
          product_description: "Adorable chandheri silk embroiderd kurti set with net duppatta",
          website_url: "https://www.meesho.com/adorable-chandheri-silk-embroiderd-kurti-set-with-net-duppatta/p/67eeex",
          product_img: "https://images.meesho.com/images/products/375226233/jkm6x_512.webp",
        },
        {
          company_name: "Manyawar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description: "Sapphire Blue Paisley Design Saree",
          website_url: "https://www.manyavar.com/en-in/saree/sapphire-blue-paisley-design-saree/UC112848.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/151222-1-546_13-05-2021-14-32-2:650x900",
        },
        {
          company_name: "Manyawar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description: "Coral Blue Floral Art Nouveau Patterned Bridal Lehenga.",
          website_url: "https://www.manyavar.com/en-in/lehenga/coral-blue-floral-art-nouveau-patterned-bridal-lehenga/UC115395.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/ULB4549V%20434-426_01_12-05-2021-18-03:283x395",
        },
        {
          company_name: "Manyawar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description: "Emerald Elegance Georgette with Mirror and Sequin Stitched Suit.",
          website_url: "https://www.manyavar.com/en-in/indo-western/emerald-elegance-georgette-with-mirror-and-sequin-stitched-suit/UC127016.html",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/NMSAS6612_436-SEA%20GREEN_101.19038_28-05-2024-13-49:650x900",
        },
        {
          company_name: "Manyawar",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScLRs1aPWFEkTiHkuOgMXVNGWXGoMEhQr03w&s",
          product_description: "Geranium Pink Bel Buti Patterned Bridal Lehenga",
          website_url: "https://manyavar.scene7.com/is/image/manyavar/ULB4731_414-PINK.5031_23-09-2023-17-21:650x900",
          product_img: "https://manyavar.scene7.com/is/image/manyavar/ULB4495-415_K_29-08-2023-13-22:650x900",
        },
      
        // Books
        {
          company_name: "Meesho",
          profile_pic: "https://images.moneycontrol.com/static-mcnews/2023/06/Meesho-682x435.jpg?impolicy=website&width=1600&height=900",
          product_description: "5 Books Set Combo Set {English Paperback.",
          website_url: "https://www.meesho.com/5-books-set-combo-set-english-paperback/p/5jawc9",
          product_img: "https://images.meesho.com/images/products/334752057/ieify_512.webp",
        },
        {
          company_name: "Flipkart",
          profile_pic: "https://i.pinimg.com/originals/aa/70/8d/aa708d1f97a04f6f5a208213f89e1e67.png",
          product_description: "The Complete Novel of Sherlock Holmes  (English, Paperback, Doyle Arthur Conan)",
          website_url: "https://www.flipkart.com/complete-novel-sherlock-holmes/p/itm297f1df03db51?pid=9788175994317&lid=LSTBOK9788175994317H3GNJG&marketplace=FLIPKART&q=novels&store=bks&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=fa4365d1-8068-453a-821c-2b10f09d4d7e.9788175994317.SEARCH&ppt=sp&ppn=sp&ssid=bng17srmb40000001725873804145&qH=f3221bc44ebd23a6",
          product_img: "https://rukminim2.flixcart.com/image/612/612/xif0q/book/j/f/q/-original-imagnhh9gsj5hkkt.jpeg?q=70",
        },
        {
          company_name: "Amazon",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
          product_description: "Shrimad Bhagwat Geeta Yatharoop (Hindi)",
          website_url: "https://www.amazon.in/s?k=books+bhagwat+geeta",
          product_img: "https://i.pinimg.com/736x/c1/a1/e6/c1a1e6456603d2354118db3a56c10d00.jpg",
        },
        {
          company_name: "Amazon",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuVHnOHxw4UwNMQR2hJIWYINqMOf85mCDDWw&s",
          product_description: "Kafka on the Shore [Paperback] Murakami, Haruki",
          website_url: "https://www.amazon.in/Kafka-Shore-Vintage-Haruki-Murakami/dp/0099458322/ref=sr_1_9?sr=8-9",
          product_img: "https://m.media-amazon.com/images/I/81tdbrewW0L._SY425_.jpg",
        },
        {
          company_name: "Flipkart",
          profile_pic: "https://i.pinimg.com/originals/aa/70/8d/aa708d1f97a04f6f5a208213f89e1e67.png",
          product_description: "The Kite Runner  (English, Paperback, Hosseini Khaled)",
          website_url: "https://www.flipkart.com/the-kite-runner/p/itmfc9k4w6qmryzp?pid=9781408824856&lid=LSTBOK9781408824856ZSGWZW&marketplace=FLIPKART&q=kiterunner&store=bks&srno=s_1_8&otracker=search&otracker1=search&fm=Search&iid=c57d3198-ee07-48e4-a376-3fd65fb207c3.9781408824856.SEARCH&ppt=sp&ppn=sp&ssid=bdu6j59lm80000001725874150188&qH=1c5c1f510d5c83dc",
          product_img: "https://rukminim2.flixcart.com/image/612/612/l1dwknk0/book/v/k/j/the-kite-runner-original-imagcy8ztzwgfnsj.jpeg?q=70",
        },
      
        // Services (Like Zomato/Swiggy)
        {
          company_name: "Zomato",
          profile_pic: "https://i.pinimg.com/736x/f4/34/e3/f434e30f1c5a170fc4700661cc99c3ab.jpg",
          product_description: "Delivering delicious meals to your doorstep.",
          website_url: "https://www.zomato.com/",
          product_img: "https://i.pinimg.com/736x/d4/ff/49/d4ff497e78a5b3752f1f6d56cc9c9f5f.jpg",
        },
        {
          company_name: "Swiggy",
          profile_pic: "https://1000logos.net/wp-content/uploads/2021/05/Swiggy-logo.jpg",
          product_description: "Delivering Happiness at your Doorsteps.",
          website_url: "https://www.swiggy.com/",
          product_img: "https://i.pinimg.com/564x/f3/e7/cb/f3e7cb1b5a54dd848602b8f100bfdeba.jpg",
        },
        {
          company_name: "Blinkit",
          profile_pic: "https://play-lh.googleusercontent.com/kXJYGrvy4pvHwzw6tMgf-KPthnPDg4RvvoOTgffwSuHCUL63WVxaj3ojX3ADBS0UiD0=w600-h300-pc0xffffff-pd",
          product_description: "Blinkit: Everything delivered in minutes. Let's Blink it",
          website_url: "https://blinkit.com/",
          product_img: "https://i.pinimg.com/564x/e8/eb/be/e8ebbe98fcaa36f61a99b564f55d1ebf.jpg",
        },
        {
          company_name: "Urban Company",
          profile_pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/UrbanClap_Logo.png/2048px-UrbanClap_Logo.png",
          product_description: "a sure-shot destination for all your service needs",
          website_url: "https://www.urbancompany.com/delhi-ncr",
          product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwkphDyosOC2lrkSeY8jEWKKQPMq-DNedsxA&s",
        },
        {
          company_name: "Domino's",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRjWcQk-SflP3Yg5vbOxiCsoKuhxfRqM93PA&s",
          product_description: "Dil, Dosti, Domino's! with The promise of 30 minutes or free.",
          website_url: "https://pizzaonline.dominos.co.in/",
          product_img: "https://i.pinimg.com/736x/58/4f/62/584f62f1bf619324a0596a392c8784ab.jpg",
        },
      
        // Job Seeking Websites (Like Internshala)
        {
          company_name: "Internshala",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwG-rqfcfXUR0aflbXpDSq-VZhnT1TgKhEjw&s",
          product_description: "To equip every student with practical skills and exposure so that they can build their dream careers.",
          website_url: "https://internshala.com/",
          product_img: "https://i.pinimg.com/736x/f3/df/37/f3df3775d7690ec871d2fd4ded11c85a.jpg",
        },
        {
          company_name: "Glass Door",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8a1Cfl2G7dqZlbStoFb3YapqlrWS9-dUMLA&s",
          product_description: "Explore job opportunities in every industry.",
          website_url: "https://www.glassdoor.co.in/Job/intern-jobs-SRCH_KO0,6.htm",
          product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw2DIG1490FsB6jFviGjdKckmKYH78cQMi0Q&s",
        },
        {
          company_name: "Career Launchpad",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcNfjaf6YiTduVfMXJG41KQ7FDv93xCHpJsq6woYsajyIzbqYHRLgW4EsAw3Q8jzm1yys&usqp=CAU",
          product_description: "Helping fresh graduates find their dream jobs.",
          website_url: "https://www.careerlaunchpad.org/",
          product_img: "https://members.asu.org.au/images/ASU%20Career%20Launchpad/ACL-Banner.png",
        },
        {
          company_name: "InternHub",
          profile_pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCFWG2BhP-sv2WhM_xgW3_n660cDyZxQxEbw&s",
          product_description: "Connecting students with top employers for internships.",
          website_url: "https://www.internhub.in/",
          product_img: "https://cdn.dorik.com/6118c560884caf0012fb364e/images/2-xVyTH.png",
        },
        {
          company_name: "Naukri",
          profile_pic: "https://www.logoshape.com/wp-content/uploads/2024/03/Naukri-vector-logo.jpg",
          product_description: "Explore Your Career Across Different Locations In Your Preferred Industry.",
          website_url: "https://www.naukri.com/",
          product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHKxHJBSM36UR1RY7ZAi3yLl8QD2sJnhvOTg&s",
        },
  ];

  export default dummyAdData;